# OpenCV fork for FirePick Delta / FireSight - Currently performs windows cross-compile and auto-deploys.
# .travis.yml script by Neil Jansen / njansen1@gmail.com with cross-compiling help from Armin van der Togt and others.
# 2014-11-27: Initial commit
# 2015-02-05: Starting process of adding in linux cross-compile via build matrix

language: cpp
compiler:
  - gcc
install:
  - sudo apt-get update -y
  - sudo apt-get install -y gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 binutils-mingw-w64-x86-64 mingw-w64-dev
  - sudo apt-get install -y cmake
script:
  - mkdir target
  - cd target
  - cmake .. -DCMAKE_TOOLCHAIN_FILE=../mingw-w64.cmake -DBUILD_DOCS=0 -DENABLE_PRECOMPILED_HEADERS=0 -DBUILD_TESTS=0 -DBUILD_PERF_TESTS=0 -DBUILD_WITH_DEBUG_INFO=0 -DBUILD_EXAMPLES=0 -DBUILD_SHARED_LIBS=1
  - make
  - make install
before_deploy:
  - cd install
  - zip opencv.zip -r .
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: rA2xeLl0ntVnI+lYeb+lAYkUKxI6aJteFinXilMHk3WyEa06i70snzXTUc78ch+5FkO6ryZf5hW9dPku57d1zkZHRAUKXq/qR9Q3Q7q1eK3cvHhYW54zKcwsalpsYMa0FI9c20QsgEnPoN4+50Vh0ObzM0Pp6F9qjr29fv1/2Xs=
  file: opencv.zip
  on:
    tags: true
    repo: firepick-delta/opencv
    branch: heads/mingw-w64
